In [1]:
# import relevant libraries and data

import pandas as pd
import numpy as np

# read in the data

data = "/Users/alexandreribeiro/Downloads/Training.csv"

df = pd.read_csv(data)

In [2]:
df.sample(10)

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
3097        0          0                     0                    0   
4568        0          1                     0                    0   
3252        0          0                     0                    0   
3291        0          0                     0                    0   
2162        0          0                     0                    0   
1605        0          1                     0                    0   
262         0          0                     0                    0   
4192        0          0                     0                    0   
2913        0          0                     0                    0   
2516        0          0                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
3097          0       0           1             0        0                 0   
4568          0       1           1             0        0                 0   
3252          0       0           0             0        0                 0   
3291          0       0           0             0        1                 0   
2162          0       0           0             0        1                 0   
1605          0       0           0             0        0                 0   
262           0       1           0             0        0                 0   
4192          0       0           0             0        0                 0   
2913          0       0           0             1        1                 1   
2516          0       1           0             0        0                 0   

      ...  scurring  skin_peeling  silver_like_dusting  small_dents_in_nails  \
3097  ...         0             0                    0                     0   
4568  ...         0             0                    0                     0   
3252  ...         0             0                    0                     0   
3291  ...         0             0                    0                     0   
2162  ...         0             0                    0                     0   
1605  ...         0             0                    0                     0   
262   ...         0             0                    0                     0   
4192  ...         0             0                    0                     0   
2913  ...         0             0                    0                     0   
2516  ...         0             0                    0                     0   

      inflammatory_nails  blister  red_sore_around_nose  yellow_crust_ooze  \
3097                   0        0                     0                  0   
4568                   0        0                     0                  0   
3252                   0        0                     0                  0   
3291                   0        0                     0                  0   
2162                   0        0                     0                  0   
1605                   0        0                     0                  0   
262                    0        0                     0                  0   
4192                   0        0                     0                  0   
2913                   0        0                     0                  0   
2516                   0        0                     0                  0   

                         prognosis  Unnamed: 133  
3097                   Hepatitis D           NaN  
4568                        Dengue           NaN  
3252  Paralysis (brain hemorrhage)           NaN  
3291                      Migraine           NaN  
2162                      Migraine           NaN  
1605                          Acne           NaN  
262                    Common Cold           NaN  
4192                 Hypertension            NaN  
2913                          GERD           NaN  
2516                       Malaria           NaN  

[10 rows x 134 columns]

In [3]:
# Remove last column

df = df.iloc[:, :-1]

### Baseline Model

- Separating the features from the target variable.

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Split the data into features (X) and target (y)
X = df.drop(columns=['prognosis'])
y = df['prognosis']

#### Perform Train-Test Split

- We split the data into training and testing sets to evaluate the model’s performance on unseen data.

In [9]:
# Perform the train-test split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

- Apply PCA to reduce the number of features while retaining most of the variance in the data.

In [14]:
from sklearn.decomposition import PCA

# Apply PCA

pca = PCA(n_components=0.95)  # Keep 95% of variance
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

#### Train and Evaluate the KNN Model on PCA-Transformed Data

- Train and evaluate a KNN model on the PCA-transformed data to assess its performance.

In [12]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Train the KNN model on PCA-transformed data
knn_pca = KNeighborsClassifier(n_neighbors=5)
knn_pca.fit(X_train_pca, y_train)

# Predict on the PCA test set
y_pred_pca = knn_pca.predict(X_test_pca)

# Evaluate the PCA model
pca_accuracy = accuracy_score(y_test, y_pred_pca)
pca_conf_matrix = confusion_matrix(y_test, y_pred_pca)
pca_class_report = classification_report(y_test, y_pred_pca)

pca_accuracy, pca_conf_matrix, pca_class_report

(1.0,
 array([[18,  0,  0, ...,  0,  0,  0],
        [ 0, 30,  0, ...,  0,  0,  0],
        [ 0,  0, 24, ...,  0,  0,  0],
        ...,
        [ 0,  0,  0, ..., 26,  0,  0],
        [ 0,  0,  0, ...,  0, 22,  0],
        [ 0,  0,  0, ...,  0,  0, 34]]),
 '                                         precision    recall  f1-score   support\n\n(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        18\n                                   AIDS       1.00      1.00      1.00        30\n                                   Acne       1.00      1.00      1.00        24\n                    Alcoholic hepatitis       1.00      1.00      1.00        25\n                                Allergy       1.00      1.00      1.00        24\n                              Arthritis       1.00      1.00      1.00        23\n                       Bronchial Asthma       1.00      1.00      1.00        33\n                   Cervical spondylosis       1.00      1.00      1.00        23\n   

In [13]:
# Print accuracy

print(f"Accuracy: {pca_accuracy:.2f}")

# Print confusion matrix

print("Confusion Matrix:")
print(pca_conf_matrix)

# Print classification report

print("\nClassification Report:")
print(pca_class_report)

Accuracy: 1.00
Confusion Matrix:
[[18  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 22  0]
 [ 0  0  0 ...  0  0 34]]

Classification Report:
                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        18
                                   AIDS       1.00      1.00      1.00        30
                                   Acne       1.00      1.00      1.00        24
                    Alcoholic hepatitis       1.00      1.00      1.00        25
                                Allergy       1.00      1.00      1.00        24
                              Arthritis       1.00      1.00      1.00        23
                       Bronchial Asthma       1.00      1.00      1.00        33
                   Cervical spondylosis       1.00      1.00      1.00        23
                            Chicken pox       1.00      1

Summary

- Accuracy: The model achieved an accuracy of 100%, which means all predictions were correct.
- Confusion Matrix: Shows that there were no misclassifications for any of the classes.
- Classification Report: The precision, recall, and F1-scores for all classes are 1.00, indicating perfect predictions for each disease.

In [17]:
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# Create a pipeline that includes scaling, PCA, and KNN

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=0.95)),
    ('knn', KNeighborsClassifier(n_neighbors=5))
])

# Define cross-validation strategy

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Perform cross-validation
cv_scores = cross_val_score(pipeline, X, y, cv=cv, scoring='accuracy')

# Print cross-validation results

print("Cross-Validation Scores:", cv_scores)
print("Mean Accuracy:", cv_scores.mean())
print("Standard Deviation:", cv_scores.std())

Cross-Validation Scores: [1. 1. 1. 1. 1.]
Mean Accuracy: 1.0
Standard Deviation: 0.0


In [18]:
# Fit PCA to the training data

pca.fit(X_train)

# Explained variance by each component

explained_variance = pca.explained_variance_ratio_
print("Explained Variance Ratio by Each Component:")
print(explained_variance)

Explained Variance Ratio by Each Component:
[0.1229062  0.10451454 0.06945006 0.06551529 0.05194827 0.03955351
 0.0366009  0.0347184  0.03361662 0.0285759  0.02545734 0.0243045
 0.02394928 0.02160191 0.02031516 0.01816544 0.01761187 0.0170179
 0.01632362 0.01508749 0.0147987  0.01410304 0.01354995 0.01319382
 0.012729   0.01177419 0.01080618 0.01024391 0.00984841 0.00966523
 0.00903063 0.0084303  0.0081462  0.00709721 0.00648061 0.00619898]
